version: '3.8'

services:
  mongo:
    image: mongo:4.4.3
    container_name: 'mongo'
    environment:
      - MONGO_INITDB_DATABASE=payments
      - MONGO_INITDB_ROOT_USERNAME=root
      - MONGO_INITDB_ROOT_PASSWORD=root123
    restart: always
    volumes:
      - ./init-mongo.js:/docker-entrypoint-initdb.d/init-mongo.js:ro
      - ./mongo-volume:/data/db
    ports:
      - '27017-27019:27017-27019'
  elastic:
    image: docker.elastic.co/elasticsearch/elasticsearch:7.12.1
    container_name: 'elastic'
    environment:
      - discovery.type=single-node
    restart: always
    ports:
      - '9200:9200'

